# Generated by Django 6.0.2 on 2026-02-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='is_pii',
            field=models.BooleanField(default=False),
        ),
    ]
